### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by robfrank**
- strip out php 5.4, due to composer error:
 Problem 1
    - Installation request for satooshi/php-coveralls dev-master -> satisfiable by satooshi/php-coveralls[dev-master].
    - satooshi/php-coveralls dev-master requires php >=5.5 -> your PHP version (5.4.37) does not satisfy that requirement.

- tests are fine only against 1.7.10 
- added support for SNAPSHOTS

### CODE REVIEW

**Comment by Ostico** [comment]
@robfrank the driver must be compatibile with PHP 5.4, i test this code on 3 different version of PHP and it works, so i think there is an issue on your side

**Comment by smolinari** [comment]
Why must it be compatible with PHP5.4? PHP5.4 is EOL. So is PHP5.5 for that matter. 

Or did you mean "should be compatible"?

Scott

**Comment by Ostico** [comment]
@smolinari , php 5.4 is the 30% of overall php running versions.

It must be supported.

https://w3techs.com/technologies/details/pl-php/5/all

**Comment by robfrank** [comment]
@Ostico ok, it was travis. If you can take the PR and do your changes will be beautiful

**Pull request merged**
